# Reference: https://github.com/tqwewe/tailwind-classes-sorter
variants_order:
  - custom # this is a special variant so that only custom variants have index 0
  - sm
  - md
  - lg
  - xl
  - 2xl
  - first
  - last
  - odd
  - even
  - hover
  - focus
  - focus-visible
  - group-hover
  - group-focus
  - focus-within
  - disabled
  - checked
  - active
  - visited
  - dark
  - motion-safe
  - motion-reduce

classes_order:
  # this is a special group so that custom classes get index 0
  custom:
    - custom
  layout:
    - static
    - fixed
    - absolute
    - relative
    - container
    - box-content
    - block
    - inline-block
    - inline
    - flex
    - inline-flex
    - table
    - table-cell
    - table-row
    - flow-root
    - grid
    - contents
    - hidden
    - float-right
    - float-left
    - float-none
    - clear-both
    - object-cover
    - object-center
    - overflow-auto
    - overflow-hidden
    - overflow-x-auto
    - overflow-y-auto
    - overflow-x-hidden
    - overflow-x-scroll
    - overflow-y-scroll
    - columns-2
    - left-0
    - left-1
    - left-2
    - left-4
    - left-8
    - left-12
    - left-16
    - left-20
    - left-24
    - left-28
    - left-1/2
    - left-2/5
    - left-full
    - right-0
    - right-1
    - right-2
    - right-4
    - right-8
    - right-12
    - right-16
    - right-1/2
    - top-0
    - top-1
    - top-2
    - top-3
    - top-4
    - top-6
    - top-8
    - top-12
    - top-16
    - top-20
    - top-1/2
    - top-1/3
    - top-1/5
    - top-2/5
    - top-3/10
    - top-full
    - bottom-0
    - bottom-2
    - bottom-3
    - bottom-4
    - bottom-8
    - bottom-20
    - -bottom-1
    - -bottom-2
    - -bottom-4
    - -bottom-8
    - -bottom-20
    - bottom-1/2
    - bottom-full
    - visible
    - invisible
    - z-0
    - z-10
    - z-20
    - z-30
    - z-40
    - z-50
    - z-99
    - z-100
    - z-101
    - z-102
    - z-103
    - z-999
    - z-9999
    - z-max
  flexbox_and_grid:
    - flex-row
    - flex-row-reverse
    - flex-col
    - flex-col-reverse
    - flex-wrap
    - flex-nowrap
    - flex-1
    - flex-auto
    - flex-none
    - flex-grow
    - flex-shrink-0
    - flex-basis-full
    - flex-basis-1/3
    - order-first
    - grid-cols-1
    - grid-cols-2
    - grid-cols-3
    - gap-x-0
    - gap-3
    - gap-4
    - gap-8
    - gap-x-36
    - justify-start
    - justify-end
    - justify-center
    - justify-between
    - justify-around
    - content-center
    - items-start
    - items-end
    - items-center
    - items-baseline
  sizing:
    - w-0
    - w-1
    - w-2
    - w-3
    - w-4
    - w-5
    - w-6
    - w-7
    - w-8
    - w-9
    - w-10
    - w-12
    - w-16
    - w-20
    - w-24
    - w-28
    - w-32
    - w-36
    - w-40
    - w-48
    - w-64
    - w-80
    - w-96
    - w-auto
    - w-px
    - w-1/2
    - w-1/3
    - w-2/3
    - w-1/4
    - w-1/5
    - w-2/5
    - w-3/5
    - w-4/5
    - w-5/6
    - w-1/12
    - w-5/12
    - w-11/12
    - w-full
    - w-max
    - min-w-0
    - min-w-4
    - min-w-5
    - min-w-8
    - min-w-20
    - min-w-32
    - min-w-40
    - min-w-48
    - min-w-64
    - min-w-96
    - min-w-full
    - max-w-0
    - max-w-2
    - max-w-20
    - max-w-48
    - max-w-64
    - max-w-96
    - max-w-128
    - max-w-192
    - max-w-full
    - max-w-none
    - max-w-3/4
    - max-w-11/12
    - h-0
    - h-1
    - h-2
    - h-3
    - h-4
    - h-5
    - h-6
    - h-7
    - h-8
    - h-9
    - h-10
    - h-12
    - h-14
    - h-16
    - h-20
    - h-24
    - h-32
    - h-36
    - h-40
    - h-44
    - h-48
    - h-64
    - h-72
    - h-96
    - h-128
    - h-192
    - h-auto
    - h-px
    - h-1/2
    - h-1/3
    - h-4/5
    - h-full
    - min-h-4
    - min-h-5
    - min-h-8
    - min-h-20
    - min-h-24
    - min-h-28
    - min-h-32
    - min-h-48
    - min-h-64
    - min-h-96
    - min-h-full
    - max-h-0
    - max-h-2
    - max-h-4
    - max-h-7
    - max-h-16
    - max-h-24
    - max-h-28
    - max-h-48
    - max-h-64
    - max-h-128
    - max-h-full
  spacing:
    - m-0
    - m-1
    - m-2
    - m-3
    - m-4
    - m-6
    - m-8
    - mx-0
    - mx-1
    - mx-2
    - mx-3
    - mx-4
    - mx-5
    - mx-6
    - mx-8
    - mx-12
    - mx-auto
    - -mx-1
    - -mx-2
    - my-0
    - my-1
    - my-2
    - my-3
    - my-4
    - my-5
    - my-6
    - my-7
    - my-8
    - my-10
    - my-12
    - my-16
    - my-px
    - ml-0
    - ml-1
    - ml-2
    - ml-3
    - ml-4
    - ml-5
    - ml-6
    - ml-8
    - ml-10
    - ml-12
    - ml-16
    - ml-24
    - ml-32
    - ml-48
    - ml-52
    - ml-56
    - ml-64
    - ml-auto
    - mr-0
    - mr-1
    - mr-2
    - mr-3
    - mr-4
    - mr-6
    - mr-8
    - mr-10
    - mr-12
    - mr-16
    - mr-24
    - mt-0
    - mt-1
    - mt-2
    - mt-3
    - mt-4
    - mt-5
    - mt-6
    - mt-7
    - mt-8
    - mt-12
    - mt-16
    - mt-24
    - mt-auto
    - -mt-4
    - mb-0
    - mb-1
    - mb-2
    - mb-3
    - mb-4
    - mb-5
    - mb-6
    - mb-7
    - mb-8
    - mb-9
    - mb-12
    - mb-16
    - mb-24
    - mb-32
    - mb-48
    - mb-auto
    - p-0
    - p-1
    - p-2
    - p-3
    - p-4
    - p-5
    - p-6
    - p-8
    - p-12
    - px-0
    - px-1
    - px-2
    - px-3
    - px-4
    - px-5
    - px-6
    - px-8
    - px-12
    - px-16
    - px-20
    - px-24
    - py-0
    - py-1
    - py-2
    - py-3
    - py-4
    - py-5
    - py-6
    - py-7
    - py-8
    - py-12
    - py-16
    - py-32
    - pl-0
    - pl-1
    - pl-2
    - pl-3
    - pl-4
    - pl-6
    - pl-7
    - pl-8
    - pl-12
    - pl-16
    - pl-24
    - pl-64
    - pr-0
    - pr-1
    - pr-2
    - pr-3
    - pr-4
    - pr-6
    - pr-8
    - pr-12
    - pr-16
    - pt-0
    - pt-1
    - pt-2
    - pt-3
    - pt-4
    - pt-5
    - pt-6
    - pt-7
    - pt-8
    - pt-9
    - pt-12
    - pt-16
    - pt-24
    - pt-32
    - pt-48
    - pb-0
    - pb-1
    - pb-2
    - pb-3
    - pb-4
    - pb-5
    - pb-6
    - pb-7
    - pb-8
    - pb-9
    - pb-12
    - pb-16
    - pb-24
    - pb-32
    - pb-96
  typography:
    - font-sans
    - text-3xs
    - text-2xs
    - text-xs
    - text-sm
    - text-base
    - text-lg
    - text-xl
    - text-2xl
    - text-4xl
    - text-5xl
    - text-none
    - italic
    - not-italic
    - font-thin
    - font-extralight
    - font-light
    - font-normal
    - font-medium
    - font-semibold
    - font-bold
    - font-extrabold
    - font-black
    - tracking-tight
    - leading-6
    - leading-7
    - leading-8
    - leading-9
    - leading-none
    - leading-tight
    - leading-normal
    - leading-relaxed
    - leading-loose
    - list-none
    - list-disc
    - list-decimal
    - list-inside
    - list-square
    - text-left
    - text-center
    - text-right
    - text-black
    - underline
    - line-through
    - no-underline
    - uppercase
    - capitalize
    - truncate
    - align-baseline
    - align-top
    - align-middle
    - align-bottom
    - align-text-top
    - whitespace-normal
    - whitespace-nowrap
    - whitespace-pre-line
  colors:
    # Please note that we use a different color system than is usual in Tailwind. You will want to replace this section
    # with your colour palette classes.
    - fg-allports
    - fg-alto
    - fg-amber
    - fg-anakiwa
    - fg-aqua
    - fg-aqua-haze
    - fg-athens-gray
    - fg-bahama-blue
    - fg-black
    - fg-black-10
    - fg-black-20
    - fg-black-30
    - fg-black-40
    - fg-black-50
    - fg-black-60
    - fg-black-70
    - fg-black-80
    - fg-black-90
    - fg-black-marlin
    - fg-blaze-orange
    - fg-blue-chill
    - fg-bondi-blue
    - fg-boulder
    - fg-broom
    - fg-brown
    - fg-carnation
    - fg-cerulean
    - fg-chalet-green
    - fg-deep-cerulean
    - fg-deep-sea-green
    - fg-denim
    - fg-dodger-blue
    - fg-dove-gray
    - fg-dusty-gray
    - fg-emperor
    - fg-fountain-blue
    - fg-geyser
    - fg-gray
    - fg-grenadier
    - fg-guardsman-red
    - fg-jelly-bean
    - fg-lima
    - fg-link-water
    - fg-mine-shaft
    - fg-my-sin
    - fg-mystic
    - fg-near-ochre
    - fg-nepal
    - fg-nobel
    - fg-orange-peel
    - fg-orient
    - fg-outer-space
    - fg-pastel-green
    - fg-pelorous
    - fg-picasso
    - fg-picton-blue
    - fg-pistachio
    - fg-red-orange
    - fg-robins-egg-blue
    - fg-saffron
    - fg-shakespeare
    - fg-silver
    - fg-silver-chalice
    - fg-slate-gray
    - fg-supernova
    - fg-teal-blue
    - fg-tia-maria
    - fg-transparent
    - fg-trinidad
    - fg-tropical-blue
    - fg-venice-blue
    - fg-viking
    - fg-white
    - fg-white-10
    - fg-white-20
    - fg-white-30
    - fg-white-40
    - fg-white-50
    - fg-white-60
    - fg-white-70
    - fg-white-80
    - fg-white-90
    - fg-wild-sand
    - fg-william
    - bg-transparent
    - bg-black
    - bg-white
    - bg-none
    - bg-alabaster
    - bg-allports
    - bg-alto
    - bg-amber
    - bg-anakiwa
    - bg-aqua-haze
    - bg-astronaut-blue
    - bg-athens-gray
    - bg-atlantis
    - bg-bahama-blue
    - bg-black
    - bg-black-05
    - bg-black-10
    - bg-black-20
    - bg-black-30
    - bg-black-40
    - bg-black-50
    - bg-black-60
    - bg-black-70
    - bg-black-80
    - bg-black-90
    - bg-black-marlin
    - bg-blaze-orange
    - bg-blue
    - bg-blue-chill
    - bg-bondi-blue
    - bg-boulder
    - bg-broom
    - bg-catskill-white
    - bg-cerulean
    - bg-christi
    - bg-chrome-white
    - bg-deep-cerulean
    - bg-deep-cerulean-70
    - bg-dove-gray
    - bg-dusty-gray
    - bg-gallery
    - bg-geyser
    - bg-gorse
    - bg-gray
    - bg-guardsman-red
    - bg-jelly-bean
    - bg-light-lima
    - bg-lima
    - bg-limed-spruce-90
    - bg-link-water
    - bg-mercury
    - bg-midnight-80
    - bg-milk-punch
    - bg-mine-shaft
    - bg-mystic
    - bg-nobel
    - bg-orange-peel
    - bg-orient
    - bg-outer-space
    - bg-pastel-green
    - bg-pelorous
    - bg-picton-blue
    - bg-pinky-violet
    - bg-pistachio
    - bg-robins-egg-blue
    - bg-romantic
    - bg-royal-blue
    - bg-shakespeare
    - bg-silver
    - bg-silver-chalice
    - bg-steel-blue-40
    - bg-transparent
    - bg-trinidad
    - bg-tropical-blue
    - bg-venice-blue
    - bg-venice-blue-60
    - bg-white
    - bg-white-10
    - bg-white-20
    - bg-white-30
    - bg-white-40
    - bg-white-50
    - bg-white-60
    - bg-white-70
    - bg-white-80
    - bg-white-90
    - bg-wild-sand
    - bg-william
    - bg-gradient-to-t
    - from-gray-50
    - to-transparent
  borders:
    - rounded-sm
    - rounded
    - rounded-md
    - rounded-lg
    - rounded-2xl
    - rounded-3xl
    - rounded-full
    - rounded-t-none
    - rounded-r-none
    - rounded-b-none
    - rounded-l-none
    - rounded-t
    - border
    - border-0
    - border-2
    - border-3
    - border-4
    - border-6
    - border-8
    - border-12
    - border-16
    - border-l
    - border-l-4
    - border-r
    - border-r-6
    - border-t
    - border-t-0
    - border-t-2
    - border-t-3
    - border-t-6
    - border-b
    - border-b-0
    - border-b-2
    - border-b-6
    - border-dashed
    - border-dotted
    - border-none
    - border-solid
    - b-alto
    - b-amber
    - b-aqua
    - b-astral
    - b-astronaut-blue
    - b-bahama-blue
    - b-black
    - b-black-10
    - b-black-20
    - b-black-30
    - b-black-40
    - b-black-50
    - b-black-60
    - b-black-70
    - b-black-80
    - b-black-90
    - b-black-marlin
    - b-blaze-orange
    - b-blue-chill
    - b-bondi-blue
    - b-boulder
    - b-casper
    - b-cerulean
    - b-christi
    - b-deep-cerulean
    - b-dove-gray
    - b-dusty-gray
    - b-geyser
    - b-granny-smith
    - b-gray
    - b-grenadier
    - b-jelly-bean
    - b-key-lime-pie
    - b-lima
    - b-mercury
    - b-nobel
    - b-orange-peel
    - b-picton-blue
    - b-pinky-violet
    - b-pistachio
    - b-robins-egg-blue
    - b-scorpion
    - b-shakespeare
    - b-silver
    - b-silver-chalice
    - b-transparent
    - b-trinidad
    - b-venice-blue
    - b-white
    - b-white-10
    - b-white-20
    - b-white-30
    - b-white-40
    - b-white-50
    - b-white-60
    - b-white-70
    - b-white-80
    - b-white-90
    - b-wild-sand
    - b-william
    - border-underline-thin
    - border-underline-thick
    - border-underline-empty
  effects:
    - shadow-sm
    - shadow-md
    - shadow-lg
    - shadow-xl
    - shadow-2xl
    - shadow-inner
    - shadow-inner-1
    - shadow-3xl
    - shadow-4xl
    - shadow-grey
    - shadow-inner-2
    - shadow-white-2
    - shadow-grey-2
    - shadow-inner-3
    - shadow-inner-border
    - shadow-white
    - shadow-5xl
    - shadow-text-default
    - shadow-text-sm
    - shadow-text-lg
    - shadow-text-white
    - shadow-text-none
    - shadow-filter-grey
    - shadow-filter-white
    - shadow-filter-black
    - opacity-0
    - opacity-20
    - opacity-30
    - opacity-40
    - opacity-50
    - opacity-60
    - opacity-70
    - opacity-80
    - opacity-90
    - opacity-100
  tables:
    - border-collapse
  animations:
    - transition-all
    - transition
    - transition-colors
    - transition-opacity
    - transition-transform
    - transition-top
    - transition-max-w
    - transition-max-h
    - duration-200
    - duration-300
    - duration-500
    - duration-700
    - ease-linear
    - ease-in
    - ease-in-out
    - animate-ping
    - transform
    - transform-gpu
    - scale-150
    - -scale-x-100
    - scale-y-50
    - scale-y-75
    - rotate-30
    - rotate-45
    - rotate-90
    - rotate-180
    - -rotate-90
    - -rotate-12
    - translate-x-1/2
    - -translate-x-1/2
    - translate-y-1/2
    - -translate-y-1/2
    - -translate-y-1/10
    - cursor-default
    - cursor-pointer
    - cursor-help
    - outline-none
    - outline-0
    - pointer-events-none
    - pointer-events-auto
    - resize-none
    - resize-y
    - resize
  filters:
    - filter
    - blur
    - drop-shadow
    - grayscale
